const texts = {
  english: {
    signIn: "Sign In",
    email: "Email",
    password: "Password",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    switch: "Switch to Nepali",
    fullName: "Full Name",
    confirmPassword: "Confirm Password",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    guardiansEmail: "Guardian's Email",
    emailVerified: "Email verified successfully",
    goToLogin: "Go To Login",
    profile: "Profile",
    personalInformation: "Personal Information",
    language: "Language",
    chooseLanguage: "Choose a language",
    notifications: "Notifications",
    enabled: "Enabled",
    progressOverview: "Progress Overview",
    dailyTasksCompleted: "Daily Tasks Completed",
    weeklyExerciseScore: "Weekly Exercise Score",
    editProfile: "Edit Profile",
    signOut: "Sign Out",
    settings: "Settings",
    languageSettings: "Language Settings",
    welcomeMessage: "Welcome to Dementia Care",
    subtitle: "Your AI-Powered Dementia Support Companion",
    features: {
      realTimeTranscription: {
        title: "Real-time Transcription",
        description: "Convert speech to text instantly",
      },
      emotionDetection: {
        title: "Emotion Detection",
        description: "Track mood changes and emotional well-being",
      },
      conversationBookmark: {
        title: "Conversation Bookmark",
        description: "Save and revisit meaningful conversations",
      },
      dailyTasks: {
        title: "Daily Tasks",
        description: "AI-generated to-do lists and reminders",
      },
      cognitiveExercises: {
        title: "Cognitive Exercises",
        description: "Brain games for mental stimulation",
      },
      progressSharing: {
        title: "Progress Sharing",
        description: "Keep family updated on condition",
      },
    },
    dailyTasks: "Daily Tasks",
    addNewTask: "Add New Task",
    enterTaskTitle: "Enter Task Title",
    enterTime: "Enter Time",
    cancel: "Cancel",
    addTask: "Add Task",
    editTask: "Edit Task",
    saveChanges: "Save Changes",
    welcome: "Welcome to Smaran",
    welcomeSub: "Your AI-Powered Support Companion",
    realTimeTranscription: "Real-Time Transcription",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    goToEmotionDetection: "Go to Emotion Detection",
    taskAdded: "Task Added",
    taskAddedSuccessfully: "Task added successfully",
    errorCreatingTask: "Error creating task",
    send: "Send",
    typeHere: "Type here",
    transcriptionPlaceholder: "Transcription will appear here",
    memoryMatchGame: "Memory Match Game",
    memoryMatchDescription: "Match pairs of cards to train your memory",
    gaauKhaneKatha: "Gaau Khane Katha",
    gaauKhaneKathaDescription: "Solve questions to enhance cognitive skills",
    sudoku: "Sudoku",
    sudokuDescription: "Play with numbers",
    cognitiveExercises: "Cognitive Exercises",
    chooseGame: "Choose a game to challenge your mind",
  },
  nepali: {
    signIn: "साइन इन",
    email: "इमेल",
    password: "पासवर्ड",
    dontHaveAccount: "खाता छैन?",
    signUp: "साइन अप",
    switch: "अंग्रेजीमा स्विच गर्नुहोस्",
    fullName: "पूरा नाम",
    confirmPassword: "पासवर्ड पुष्टि गर्नुहोस्",
    gender: "लिङ्ग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    guardiansEmail: "अभिभावकको इमेल",
    emailVerified: "इमेल सफलतापूर्वक प्रमाणित गरियो",
    goToLogin: "लगइनमा जानुहोस्",
    profile: "प्रोफाइल",
    personalInformation: "व्यक्तिगत जानकारी",
    language: "भाषा",
    chooseLanguage: "भाषा चयन गर्नुहोस्",
    notifications: "सूचनाहरू",
    enabled: "सक्षम",
    progressOverview: "प्रगति अवलोकन",
    dailyTasksCompleted: "दैनिक कार्यहरू",
    weeklyExerciseScore: "साप्ताहिक व्यायाम स्कोर",
    editProfile: "प्रोफाइल सम्पादन गर्नुहोस्",
    signOut: "साइन आउट",
    settings: "सेटिङ्गहरू",
    languageSettings: "भाषा सेटिङ्ग",
    welcomeMessage: "डिमेन्सिया केयरमा स्वागत छ",
    subtitle: "तपाईंको एआई-संचालित डिमेन्सिया समर्थन साथी",
    features: {
      realTimeTranscription: {
        title: "रियल-टाइम ट्रान्सक्रिप्सन",
        description: "भाषणलाई तुरुन्तै पाठमा रूपान्तरण गर्नुहोस्",
      },
      emotionDetection: {
        title: "भावनाको पहिचान",
        description: "मुड परिवर्तनहरू र भावनात्मक स्थिति ट्र्याक गर्नुहोस्",
      },
      conversationBookmark: {
        title: "वार्ता बुकमार्क",
        description: "महत्वपूर्ण वार्ता सुरक्षित राख्नुहोस् र पुन: हेर्नुहोस्",
      },
      dailyTasks: {
        title: "दैनिक कार्यहरू",
        description: "एआई-जनित टु-डू सूचीहरू र रिमाइन्डरहरू",
      },
      cognitiveExercises: {
        title: "संज्ञानात्मक अभ्यासहरू",
        description: "मस्तिष्क खेलहरू मानसिक उत्तेजनाको लागि",
      },
      progressSharing: {
        title: "प्रगति साझा गर्दै",
        description: "परिवारलाई स्थिति अद्यावधिक गराउनुहोस्",
      },
    },
    dailyTasks: "दैनिक कार्यहरू",
    addNewTask: "नयाँ कार्य थप्नुहोस्",
    enterTaskTitle: "कार्य शीर्षक प्रविष्ट गर्नुहोस्",
    enterTime: "समय प्रविष्ट गर्नुहोस्",
    cancel: "रद्द गर्नुहोस्",
    addTask: "कार्य थप्नुहोस्",
    editTask: "कार्य सम्पादन गर्नुहोस्",
    saveChanges: "परिवर्तनहरू सुरक्षित गर्नुहोस्",
    welcome: "स्मरण मा हजुरलाई स्वागत छ",
    welcomeSub: "तपाईंको AI-संचालित सहायता साथी",
    realTimeTranscription: "रियल-टाइम ट्रान्सक्रिप्शन",
    startRecording: "रेकर्डिङ सुरु गर्नुहोस्",
    stopRecording: "रेकर्डिङ रोक्नुहोस्",
    goToEmotionDetection: "भावना पत्ता लगाउन जानुहोस्",
    taskAdded: "कार्य थपियो",
    taskAddedSuccessfully: "कार्य सफलतापूर्वक थपियो",
    errorCreatingTask: "कार्य सिर्जना गर्दा त्रुटि",
    send: "पठाउनुहोस्",
    typeHere: "यहाँ प्रविष्ट गर्नुहोस्...",
    transcriptionPlaceholder: "ट्रान्सक्रिप्टन यहाँ देखिनेछ",
    memoryMatchGame: "स्मृति मिलान खेल",
    memoryMatchDescription:
      "तपाईंको स्मृति प्रशिक्षण गर्न कार्डको जोडी मिलाउनुहोस्",
    gaauKhaneKatha: "गाउँ खाने कथा",
    gaauKhaneKathaDescription:
      "संज्ञानात्मक सीपहरू बढाउन प्रश्नहरू समाधान गर्नुहोस्",
    sudoku: "सुडोकु",
    sudokuDescription: "संख्याहरूको साथ खेल्नुहोस्",
    cognitiveExercises: "संज्ञानात्मक अभ्यासहरू",
    chooseGame: "तपाईंको मनलाई चुनौती दिन खेल चयन गर्नुहोस्",
  },
};

export default texts;
